# -*- coding: utf-8 -*-
"""proj 109

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dHhDm92FJCtYAGefXRzordaJ0OPuvNeX
"""

from google.colab import files
data_to_load = files.upload()

import statistics
import csv 
import pandas as pd

df = pd.read_csv("StudentsPerformance.csv")
mathScore = df["math score"].tolist()
mathMean = statistics.mean(mathScore)
mathMedian = statistics.median(mathScore)
mathMode = statistics.mode(mathScore)
standardDev = statistics.stdev(mathScore) 

firstStandardDeviationStart, firstStandardDeviationEnd = mathMean - standardDev, mathMean + standardDev
secondStandardDeviationStart, secondStandardDeviationEnd = mathMean -(2 * standardDev), mathMean + (2* standardDev)
thirdStandardDeviationStart, thirdStandardDeviationEnd = mathMean -(3 * standardDev), mathMean + (3* standardDev)

thin_1_std_deviation = [result for result in mathScore if result > firstStandardDeviationStart and result < firstStandardDeviationEnd]
thin_2_std_deviation = [result for result in mathScore if result > secondStandardDeviationStart and result < secondStandardDeviationEnd]
thin_3_std_deviation = [result for result in mathScore if result > thirdStandardDeviationStart and result < thirdStandardDeviationEnd]

print(mathMean)
print(mathMedian)
print(mathMode)
print(standardDev)

print(str(len(thin_1_std_deviation)*100.0/len(mathScore)) + "% of data lies within first standard deviation")
print(str(len(thin_2_std_deviation)*100.0/len(mathScore)) + "% of data lies within second standard deviation")
print(str(len(thin_3_std_deviation)*100.0/len(mathScore)) + "% of data lies within second standard deviation")